// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpj0Lg3nBpg_ca82ZxxQ6E-kpl_MKWSgI',
    appId: '1:347454405587:web:41ff9aed77c3c2b9f20d26',
    messagingSenderId: '347454405587',
    projectId: 'e-commerseapp-7b279',
    authDomain: 'e-commerseapp-7b279.firebaseapp.com',
    storageBucket: 'e-commerseapp-7b279.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQhWPHfDBGItzM6BaEijM4E7D-HdlTSzA',
    appId: '1:347454405587:android:c361d7fee584892df20d26',
    messagingSenderId: '347454405587',
    projectId: 'e-commerseapp-7b279',
    storageBucket: 'e-commerseapp-7b279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuHX6QQTczpbSL3VvRYQiqG6aQaBcWMw',
    appId: '1:347454405587:ios:a6ac85da745a1dcef20d26',
    messagingSenderId: '347454405587',
    projectId: 'e-commerseapp-7b279',
    storageBucket: 'e-commerseapp-7b279.appspot.com',
    androidClientId: '347454405587-3i776neb06i51o6cts6ps5qkm5pr13mm.apps.googleusercontent.com',
    iosClientId: '347454405587-l058gi5vouf8vspcf8ktmotlm6cuq9k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.danastoreadminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwyuH66N9kGgsZjr48NbQCWFb13ESLsFQ',
    appId: '1:347454405587:web:96079dcfdb4fcd19f20d26',
    messagingSenderId: '347454405587',
    projectId: 'e-commerseapp-7b279',
    authDomain: 'e-commerseapp-7b279.firebaseapp.com',
    storageBucket: 'e-commerseapp-7b279.appspot.com',
  );
}
